package notifications

var (
	NEW_OPEN_TRADE_REQUEST_NOTIF = "NEW_OPEN_TRADE_REQUEST_NOTIF"
	NEW_TRADE_REQUEST_NOTIF      = "NEW_TRADE_REQUEST_NOTIF"

	TRADE_REQUEST_APPROVED_NOTIF = "TRADE_REQUEST_APPROVED_NOTIF"

	TRADE_REQUEST_REJECTED_NOTIF = "TRADE_REQUEST_REJECTED_NOTIF"

	TRADE_REQUEST_CANCELED_NOTIF = "TRADE_REQUEST_CANCELED_NOTIF"

	TRADE_REQUEST_SIGNED_NOTIF = "TRADE_REQUEST_SIGNED_NOTIF"

	TRADE_REQUEST_VESSEL_NOMINATED_NOTIF           = "TRADE_REQUEST_VESSEL_NOMINATED_NOTIF"
	TRADE_REQUEST_VESSEL_NOMINATION_APPROVED_NOTIF = "TRADE_REQUEST_VESSEL_NOMINATION_APPROVED_NOTIF"
	TRADE_REQUEST_VESSEL_NOMINATION_REJECTED_NOTIF = "TRADE_REQUEST_VESSEL_NOMINATION_REJECTED_NOTIF"

	TRADE_REQUEST_DOCUMENT_INSTRUICTIONS_SENT_NOTIF = "TRADE_REQUEST_DOCUMENT_INSTRUICTIONS_SENT_NOTIF"

	COMMENT_ADDED_NOTIF = "COMMENT_ADDED_NOTIF"

	COMMENT_ADDED_TO_DOC_NOTIF = "COMMENT_ADDED_TO_DOC_NOTIF"

	INSPECTION_WAS_CHOOSED_NOTIF = "INSPECTION_WAS_CHOOSED_NOTIF"

	SHIPPING_ADVICE_NOTIF = "SHIPPING_ADVICE_NOTIF"

	DOCUMENT_UPLOADED_NOTIF = "DOCUMENT_UPLOADED_NOTIF"
	DOCUMENT_APPROVED_NOTIF = "DOCUMENT_APPROVED_NOTIF"
	DOCUMENT_REJECTED_NOTIF = "DOCUMENT_REJECTED_NOTIF"
	DOCUMENT_RELEASED_NOTIF = "DOCUMENT_RELEASED_NOTIF"

	DOCUMENT_BILL_FILLED_NOTIF    = "DOCUMENT_BILL_FILLED"
	DOCUMENT_INVOICE_FILLED_NOTIF = "DOCUMENT_INVOICE_FILLED"

	TRADE_PAYMENT_NOTIF = "TRADE_PAYMENT_NOTIF"
	TRADE_PAYED_NOTIF   = "TRADE_PAYED_NOTIF"

	TRADE_CLOSE_NOTIF = "TRADE_CLOSE_NOTIF"

	TRADE_BID_COUNTERED_NOTIF = "TRADE_COUNTERED_NOTIF"
	TRADE_BID_DECLINED_NOTIF  = "TRADE_BID_DECLINED_NOTIF"
	TRADE_BID_ACCEPTED        = "TRADE_BID_ACCEPTED"
)
